### ISSUE TITLE
Display issue on Foundation Theme

### ISSUE THREAD

**Issue by morarchives** [zerocrates/PdfEmbedS#4]
Hello,
My site is hosted with Reclaim Hosting and is Omeka S Version 3.2.0. I am using the Foundation Theme version 1.2.4.

I have found that when the PDF view is embedded on the item show page, it does not display properly. This is the case for when using the Foundation Theme setting for Media Display for Show pages set to "Next to Metadata" and the same if I insert it into the show page [using the following code from this post. ](https://forum.omeka.org/t/display-of-other-media/9020/5)

It does display as expected on the item media page. I really need that version of it to display at the top of the item show page. Is there a way to fix this without updating Omeka? I am stuck with this version for now. Screen shots below.

I have tried both PDF module versions 1.2.0 and 1.21

Thanks for your help!

Link to Item page
https://moravianhistoricalsociety.reclaim.hosting/s/mhs/item/1621

Item Show Page with Foundation Theme settings
![image](https://user-images.githubusercontent.com/114703264/232370664-50bebfd0-8454-4282-951a-1249077d6cfb.png)

Item Show Page with inserted coding
![image](https://user-images.githubusercontent.com/114703264/232371020-b34638d4-4f2b-4a65-ad24-166341ca5fb9.png)

Item Media Page
![image](https://user-images.githubusercontent.com/114703264/232371166-c90bd53b-d5ad-4b84-90f6-6bfba43559c8.png)

**Comment by zerocrates** [comment]
What code did you add when you tried editing the view, specifically? There's a lot of code in that post.

If you end up calling `$media->render()` you should be getting the PDF viewer when you have PDF Embed installed.

**Comment by morarchives** [comment]
This was the code, which results in the third screenshot.

<?php if (count($otherMedia) > 0): ?> <div id="other-media"> <div class=
"media-embeds"> <?php foreach ($otherMedia as $media) { echo $media->render();
} ?> </div> <?php endif; ?>

**Comment by morarchives** [comment]
Oops, the second screenshot actually. It doesn’t have any controls and it
is using a small section of the page.

**Comment by zerocrates** [comment]
Can you switch back to the "added coding" version so I can look at it "live" at your link?

You could also paste your whole item/show.phtml file, with your edit, here and I can look at it. Calling `render()` should be giving you the viewer so I suspect something else is happening.

**Comment by morarchives** [comment]
Here is live link on the test site that I made visible temporarily
https://moravianhistoricalsociety.reclaim.hosting/s/stagingarea/item/4482

Here is the Code for Show file
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$galleryDisplay = (isset($mediaDisplay)) ? strpos($mediaDisplay, 'gallery')
: false;
$tracksPresent = $this->DetectTracks($itemMedia);

if ($galleryDisplay) {

$this->headLink()->appendStylesheet($this->assetUrl('vendor/lightgallery/css/lightgallery-bundle.min.css'));

$this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/lightgallery.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/show.js'));

$this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/thumbnail/lg-thumbnail.min.js'));

$this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/video/lg-video.min.js'));

$this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/pager/lg-pager.min.js'));

$this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/zoom/lg-zoom.min.js'));

    $lightMedia = [];
    $otherMedia = [];
    $whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png',
'image/svg+xml'];
    foreach ($itemMedia as $media) {
        $mediaType = $media->mediaType();
        $mediaRenderer = $media->renderer();
        if (in_array($mediaType, $whitelist) || (strpos($mediaType,
'video') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
            $lightMedia[] = $media;
        } else {
            $otherMedia[] = $media;
        }
    }
}
?>

<div class="resource-title">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>
<?php if (count($otherMedia) > 0): ?>
<div id="other-media">
    <div class="media-embeds">
    <?php
    foreach ($otherMedia as $media) {
        echo $media->render();
    }
    ?>
</div>
<?php endif; ?>
<div class="grid-x">
<?php if ($galleryDisplay): ?>
    <?php if (count($lightMedia) > 0): ?>
    <div id="itemfiles" class="<?php echo $mediaDisplay; ?>">
        <?php foreach ($lightMedia as $media): ?>
            <?php
                $mediaType = $media->mediaType();
                $mediaRenderer = $media->renderer();
                $source = ($media->originalUrl()) ? $media->originalUrl() :
$media->source();
                $subHtml = "<div class='lg-caption'>" .
$media->displayTitle() . "</div>";
            ?>

            <?php if (strpos($mediaType, 'image') !== false): ?>
                <div data-src="<?php echo $source; ?>" data-thumb="<?php
echo $escape($media->thumbnailUrl('square')); ?>" class="media resource"
data-sub-html="<?php echo $subHtml; ?>">
                    <?php echo $media->render(); ?>
                </div>
            <?php elseif (strpos($mediaRenderer, 'youtube') !== false): ?>
                <a
                    class="media resource"
                    data-src="<?php echo $source; ?>"
                    data-poster="<?php echo
$media->thumbnailDisplayUrl('square'); ?>"
                    data-sub-html="<?php echo $subHtml; ?>"
                >
                </a>
            <?php else: ?>
                <?php
                    $trackHtml = '';
                    if ($tracksPresent) {
                        $originalFilename = pathinfo($media->source(),
PATHINFO_FILENAME);
                        $trackHtml .=  '"tracks": [';
                        foreach ($otherMedia as $key => $media) {
                            $trackHtml .= $this->OutputTrack($media,
$originalFilename);
                            unset($otherMedia[$key]);
                        }
                        $trackHtml = rtrim($trackHtml, ',');
                        $trackHtml .= '],';
                    }
                ?>
                <a
                    class="media resource"
                    data-video='{"source": [{"src":"<?php echo $source;
?>", "type":"<?php echo $mediaType; ?>"}], <?php echo $trackHtml; ?>
"attributes": {"preload": false, "controls": true}}'
                    data-download-url="<?php echo $source; ?>"
                    data-poster="<?php echo
$media->thumbnailDisplayUrl('square'); ?>"
                    data-sub-html="<?php echo $subHtml; ?>"
                >
                    <img
                        class="img-responsive"
                        src="<?php echo
$media->thumbnailDisplayUrl('square'); ?>"
                    />
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
<?php else: ?>
    <?php if (count($itemMedia) > 0): ?>
    <div class="<?php echo ($embedMedia) ? 'media-embeds' : 'media-list'
?>">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo ($embedMedia) ? $media->render() : $media->linkPretty();
?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>


<?php endif; ?>

<div id="resource-values" class="<?php echo ($showLayout == 'inline') ?
'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <dl>
            <div class="property">
                <dt><?php echo $translate('Item sets'); ?></dt>
                <div class="values">
                    <?php foreach ($itemSets as $itemSet): ?>
                        <dd class="value"><a href="<?php echo
$escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle();
?></a></dd>
                   <?php endforeach; ?>
                </div>
            </div>
        </dl>
    <?php endif; ?>

    <?php if ($galleryDisplay || $mediaDisplay == 'single'): ?>
        <?php $mediaList = ($galleryDisplay) ? $otherMedia : $itemMedia; ?>
    <?php endif; ?>
    <?php if (isset($mediaList) && count($mediaList) > 0): ?>
        <dl>
            <div class="property">
                <dt><?php echo $translate('Media'); ?></dt>
                <div class="values">
                <?php foreach ($mediaList as $media): ?>
                    <dd class="value"><?php echo $media->linkPretty();
?></dd>
                <?php endforeach; ?>
                </div>
            </div>
        </dl>
    <?php endif; ?>

    <?php if (($this->siteSetting('show_attached_pages', true)) &&
($sitePages = $item->sitePages($site->id()))): ?>
        <dl>
             <div class="property">
                <dt><?php echo $translate('Site pages'); ?></dt>
                <div class="values">
                    <?php foreach ($sitePages as $sitePage): ?>
                        <dd class="value"><?php echo
$sitePage->link($sitePage->title()); ?></dd>
                    <?php endforeach; ?>
                </div>
            </div>
        </dl>
    <?php endif; ?>

    <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>
    </div>

</div>

**Comment by zerocrates** [comment]
Looks to me at the link you shared that it is the "real" embedded viewer being used there, not a static image as your screenshot seemed to show.

From there the only issue is the width. The width of `#media-embeds` is set by a style of the Foundation theme. The easiest option for you to get around it is probably going to be to take the code you added:

```
<div id="other-media">
    <div class="media-embeds">
    <?php
    foreach ($otherMedia as $media) {
        echo $media->render();
    }
    ?>
</div>
```

and just take out the `media-embeds` div:

```
<div id="other-media">
    <?php
    foreach ($otherMedia as $media) {
        echo $media->render();
    }
    ?>
</div>
```

**Comment by morarchives** [comment]
Okay, looks like that is working! Thanks for your help!

**Comment by morarchives** [comment]
Okay, one last question. How can I limit the render to just PDF or fix the
issue of how the HTML version of embedding looks?

Here is an example.
https://moravianhistoricalsociety.reclaim.hosting/s/mhs/item/3096

**Comment by zerocrates** [comment]
I can't see that page, I assume the item is not public.

But you could write your code to check the mediaType of the media before deciding to `render()` it. So you could, for example, look for an `application/pdf` media type and only call render on the media objects with that type.

**Comment by morarchives** [comment]
Try this one
https://moravianhistoricalsociety.reclaim.hosting/s/mhs/item/3095

**Comment by morarchives** [comment]
Will it affect other types of formats displaying their render? I have a mix
of records going on and want the viewer to be at the top for all of them.
But images and the PDF are the priority. The HTML are usually items hosted
at another location anyway, thus the cover image so the browsing has a
thumbnail.

Maps - images works
https://moravianhistoricalsociety.reclaim.hosting/s/mhs/item/3124

Others - the PDF works
https://moravianhistoricalsociety.reclaim.hosting/s/mhs/item/4486

**Comment by morarchives** [comment]
You can close this issue, I have removed the HTML items for now.
